name: Build and Package

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'

      - name: Build Binaries
        run: |
          mkdir -p release
          GOOS=linux GOARCH=amd64 go build -o release/berachain-exporter-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o release/berachain-exporter-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o release/berachain-exporter-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o release/berachain-exporter-windows-amd64.exe

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: release/*
